Fix k8s pipeline

diff --git a/.github/workflows/kubernetes.yaml b/.github/workflows/kubernetes.yaml
--- a/.github/workflows/kubernetes.yaml
+++ b/.github/workflows/kubernetes.yaml
@@ -19,33 +19,37 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout repo
+        uses: actions/checkout@v3
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region:            eu-central-1
+
       - name: Set up kubectl
         uses: azure/setup-kubectl@v3
         with:
           version: 'latest'
 
-      - name: Configure kubeconfig
+      - name: Update kubeconfig
         run: |
-          aws eks update-kubeconfig --region eu-central-1 --name diploma-cluster
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_DEFAULT_REGION: eu-central-1
+          aws eks update-kubeconfig \
+            --region eu-central-1 \
+            --name diploma-cluster
 
       - name: Restart selected Kubernetes resource
         run: |
           case "${{ github.event.inputs.target }}" in
             auth-service)
-              kubectl rollout restart deployment auth-service
-              ;;
+              kubectl rollout restart deployment/auth-service ;;
             shortener-service)
-              kubectl rollout restart deployment shortener-service
-              ;;
+              kubectl rollout restart deployment/shortener-service ;;
             ingress)
-              kubectl rollout restart ingress diploma-ingress
-              ;;
+              kubectl rollout restart ingress/diploma-ingress ;;
             *)
-              echo "Invalid target"
-              exit 1
-              ;;
+              echo "Invalid target: ${{ github.event.inputs.target }}" >&2
+              exit 1 ;;
           esac
